import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useState } from "react";
import { gql } from "@apollo/client";
import client from "../apollo-client";

import { Grid, CardActionArea, Box, Button, Card, CardContent, Typography } from "@mui/material";

export default function Home({ launches }) {
  const [currentLaunch, setLaunch] = useState({
    id: 0,
    mission_name: "You'll see the mission name here",
    details: "Select a mission to see the details",
    launch_site: { 
      site_name_long: "" 
    },
    links: {
      video_link: "",
      flickr_images: [],
      article_link: "https://www.spacex.com/",
    }
  });
  const [active, setActive] = useState(0);

  return (
    <div className={styles['parent-bg']}>
    <Grid container maxWidth="lg" sx={{boxShadow: 3, display: 'flex', height: '90vh', m:'auto', bgcolor:'#fff'}}>
      <Head>
        <title>SpaceX Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Cards Section */}
      <Grid item xs={4} sx={{height: "100%" }}>
        <Box sx={{ height: "10%", textAlign: 'center', pt:2}}>
          <Typography gutterBottom variant="h5" component="div">
            Last Launches
          </Typography>
        </Box>
        <Box sx={{ height: "90%" }} className={styles['scroll']}>
          {launches.map((launch) => {
            return (
              <Card sx={{ m: 1 }} key={launch.id} className={(active===launch.id) ? styles['card-selected'] : null}>
                <CardActionArea onClick={() => {
                  setLaunch(launch)
                  setActive(launch.id)
                  }}>
                  <CardContent>
                    <Grid container spacing={2}>
                      {/* Card Image */}
                      <Grid item xs={4}>
                        {
                          (launch.links.flickr_images[0]) ?
                          <img src={launch.links.flickr_images[0]} className={styles['card-image']}/>:
                          <img src="placeholder.jpg" className={styles['card-image']}/>
                        }
                      </Grid>

                      {/* Card Content */}
                      <Grid item xs={8}>
                        <Typography sx={{fontWeight: 'bold'}}>
                          {launch.mission_name}
                        </Typography>
                        <Typography variant="body2">
                          {launch.launch_site.site_name_long}
                        </Typography>
                        <Box sx={{ textAlign: "right", width: "100%", mt:1}}>
                          {(new Date(launch.launch_date_local)).toLocaleDateString()}
                        </Box>
                      </Grid>
                    </Grid>
                  </CardContent>
                </CardActionArea>
              </Card>
            );
          })}
        </Box>
      </Grid>

      {/* Mission Info Section */}
      <Grid item xs={8} sx={{ height: '100%'}}>
        {/* Mission Image */}
        <Box sx={{ height: "60%", textAlign: 'center'}}>
          {/* If there's no image we'll display a placeholder */}
          { 
            (currentLaunch.links.flickr_images[0]) ?
              <img src={currentLaunch.links.flickr_images[0]} className={styles['display-image']}/>:
              <img src="/placeholder.jpg" className={styles['display-image']}/>
          }
        </Box>

        {/* Mission Details */}
        <Box sx={{ height: "40%", textAlign: 'center', p:2 }} className={styles['scroll']}>
          <Typography gutterBottom variant="h6" component="div" sx={{fontWeight: 'bold'}}>
            {currentLaunch.mission_name}
          </Typography>
          <Typography variant="body2" color="text.secondary" sx={{mb:2}}>
            {currentLaunch.details}
          </Typography>
          {/* If there's no article we'll assign a youtube link */}
          {
            (currentLaunch.links.article_link) ?
              <a href={currentLaunch.links.article_link} target="_blank">
                <Button variant="outlined" color="secondary">See More</Button>
              </a> :
              <a href={currentLaunch.links.video_link} target="_blank">
                <Button variant="outlined" color="secondary">See More</Button>
              </a>
          }
        </Box>
      </Grid>
    </Grid>
    </div>
  );
}

// Get info from spaceX API
export async function getServerSideProps({ params }) {
  const { data } = await client.query({
    query: gql`
      {
        launchesPast(limit: 10) {
          mission_name
          launch_site {
            site_name_long
          }
          links {
            video_link
            flickr_images
            article_link
          }
          details
          launch_date_local
          id
        }
      }
    `,
  });

  return {
    props: {
      launches: data.launchesPast,
    },
  };
}
